chore: correção no quick-check

diff --git a/.github/workflows/quick-checks.yml b/.github/workflows/quick-checks.yml
--- a/.github/workflows/quick-checks.yml
+++ b/.github/workflows/quick-checks.yml
@@ -9,7 +9,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  PHP_VERSION: '8.4'
+  PHP_VERSION: '8.3'
   NODE_VERSION: '22'
   WORKING_DIR: src
 
@@ -93,9 +93,14 @@ jobs:
         if: steps.changes.outputs.php == 'true'
         working-directory: ${{ env.WORKING_DIR }}
         run: |
+          if [ ! -f ".env.testing" ]; then
+            echo "❌ .env.testing file not found"
+            exit 1
+          fi
           cp .env.testing .env
           php artisan key:generate
-          php artisan test --stop-on-failure
+          php artisan ziggy:generate
+          vendor/bin/phpunit --stop-on-failure --no-coverage
 
       - name: 📊 Build check
         if: steps.changes.outputs.js == 'true'
